### ISSUE TITLE
better formatting for github help

### ISSUE THREAD

**Issue by rabbah** [nimbella/command-sets#133]
**Describe the solution you'd like**
Improve the output of `/nc github`.
See screen shot and look at the `![]` prefixes and hyperlinks that follow.

<img width="463" alt="Screen Shot 2020-04-12 at 11 19 25 AM" src="https://user-images.githubusercontent.com/4959922/79072552-93dbd480-7caf-11ea-87e6-461e912da443.png">

**Comment by satyarohith** [comment]
Closed by #136.
