### ISSUE TITLE
corona_stats response should be re-structured

### ISSUE THREAD

**Issue by v-shant** [nimbella/command-sets#137]
currently, response block is array of array [ [ ], [ ], [ ] ] but it is array of objects  

         "blocks": [{
                 "text": {
                           "text": "*CoronaVirus :mask: Stats in India 🇮🇳 :*"  ,
                           "type": "mrkdwn"
                  },
                  "type": "section"
          },
          {
                  "fields": [
                          { "text": "Total Cases:   *10,453*", "type": "mrkdwn" },
                          { "text": "Total Cases:   *10,453*", "type": "mrkdwn" }
                   ],
                   "type": "section"
        }]

OR

         "blocks": [{
                 "text": {
                           "text": "*CoronaVirus :mask: Stats in India 🇮🇳 :*"  ,
                           "type": "mrkdwn"
                  },
                  "fields": [
                          { "text": "Total Cases:   *10,453*", "type": "mrkdwn" },
                          { "text": "Total Cases:   *10,453*", "type": "mrkdwn" }
                   ],
                   "type": "section"
        }]

this should be the actual response. it's working in slack is really a wonder. 

You can check the doc [here](https://api.slack.com/block-kit/building)

**Comment by satyarohith** [comment]
I don't see any issue in the output of `corona_stats`. 
```js
[
 {
   "type": "section",
   "text": {
     "type": "mrkdwn",
     "text": "CoronaVirus :mask: Stats Worldwide :world_map: :"
   }
 },
 {
   "type": "section",
   "fields": [
     {
       "type": "mrkdwn",
       "text": "Cases:   1,925,553"
     },
     {
       "type": "mrkdwn",
       "text": "Recovered:   452,178"
     },
     {
       "type": "mrkdwn",
       "text": "Fatalities:   119,718"
     }
   ]
 },
 {
   "type": "context",
   "elements": [
     {
       "type": "mrkdwn",
       "text": "add corona_stats to your Slack with Commander"
     },
     {
       "type": "mrkdwn",
       "text": "to see stats for a country, type corona_stats <countryName> e.g. /nc corona_stats us"
     }
   ]
 }
]
```
Are you talking about something else?

**Comment by v-shant** [comment]
thanks, @satyarohith I guess I misunderstood the response I will close this once I will be more sure if it's in the correct form.

**Comment by v-shant** [comment]
working fine, closing
