### ISSUE TITLE
Command-set to run custom app commands

### ISSUE THREAD

**Issue by niks3089** [nimbella/command-sets#17]
It would be cool to run custom slack and mattermost apps using commander. This way we can run those commands as tasks. For Slack, we would need 2 secrets to be set up. 1 is the slack-legacy token to run slack app. 

How to create such tokens and what secrets needs to be created needs to be documented in README file.

**Comment by satyarohith** [comment]
We created a Mattermost slash command to run custom commands (#24). Will reopen this when we're onto the Slack command.
