### ISSUE TITLE
tweam "add to your" message for teams

### ISSUE THREAD

**Issue by rabbah** [nimbella/command-sets#225]
This is how the "Add to your" space message appears in teams.
We should replace `msteams` with `Microsoft Teams` or just `Team` instead.

<img width="488" alt="Screen Shot 2020-09-09 at 3 47 48 PM" src="https://user-images.githubusercontent.com/4959922/92646064-dbdd4280-f2b3-11ea-8a93-8e684555453d.png">

**Comment by dengliming** [comment]
@rabbah Do you mean all the command which contains `Add to your`?

**Comment by rabbah** [comment]
Yep :)
