### ISSUE TITLE
github command set does not support enterprise api hosts

### ISSUE THREAD

**Issue by rabbah** [nimbella/command-sets#232]
The command set for github assumes github.com (api.github.com). The code needs to be parameterized to allow github hosted elsewhere.

**Comment by rabbah** [comment]
a suggested approach to dealing with this is how the `nim` cli is supporting multiple github hosts: `token@hostname` and then splitting on `@` and constructing the github url. 

you can see the `nim` patch here: https://github.com/nimbella/nimbella-cli/pull/56

**Comment by bhageena** [comment]
This CR has been included via the linked PR. Following are the ways to specify a host: 

1. Specify --host or -h while invoking the command.
2. Append the hostname to your github_token following this format: access_token@github_host. For example mysecret@example.com.
3. Create a secret with key name github_host using /nc secret_create, and add the host as the value.

If you use more than one of the approaches listed above, the precedence is decided top-down (i.e., command-line supersedes all others).
