### ISSUE TITLE
Improve formatting for times command

### ISSUE THREAD

**Issue by rabbah** [nimbella/command-sets#239]
**Is your feature request related to a problem? Please describe.**

The times command formats output in a way that is too sparse (compared to older implementation). 
![1F8A812F-B258-4F78-AA7E-1C472E582253](https://user-images.githubusercontent.com/4959922/107611720-a0ec8b80-6c12-11eb-8871-53d39a3042d7.jpeg)
![A8F568AA-BB1F-4E6B-B5DA-8F82942F2EEB](https://user-images.githubusercontent.com/4959922/107611721-a1852200-6c12-11eb-939f-419f9f8fa6d9.jpeg)

**Describe the solution you'd like**
Restore compact format.

**Comment by rabbah** [comment]
the non-tabular format appears on mobile devices only.

**Comment by bhageena** [comment]
It's been addressed via #240
