### ISSUE TITLE
bluejeans_cancel returns 500 when meeting id is specified

### ISSUE THREAD

**Issue by niks3089** [nimbella/command-sets#71]
![Screenshot 2020-03-06 at 4 01 41 PM](https://user-images.githubusercontent.com/5587829/76075990-fb717680-5fc3-11ea-9556-9719d1f262ec.png)

**Comment by satyarohith** [comment]
Probably because it's not the ID. You need to pass `-detail` to `bluejeans_list` to list their ids.

**Comment by niks3089** [comment]
Please remove the `-detail` option and have everything listed with `bluejeans_list`. That would be simpler for someone who is running the command.

**Comment by niks3089** [comment]
Can you also print the message instead of statusCode? 500 could mean a lot of things. Does the API return the error message?

**Comment by niks3089** [comment]
![Screenshot 2020-03-06 at 5 52 30 PM](https://user-images.githubusercontent.com/5587829/76083289-46df5100-5fd3-11ea-9da3-746464c0e77c.png)
Seeing the same message even with the correct meeting id?
