### ISSUE TITLE
bluejeans_create: Running just `bluejeans_create` doesn't show any upcoming meetings

### ISSUE THREAD

**Issue by niks3089** [nimbella/command-sets#85]
<img width="344" alt="Screenshot 2020-03-11 at 11 34 31 PM" src="https://user-images.githubusercontent.com/5587829/76448929-2d823e80-63f1-11ea-8d18-ef70f4d7721f.png">

This might be an expected behaviour, but do we know when the link gets expired and we can show the link in `bluejeans_list`?

**Comment by satyarohith** [comment]
It never expires - the link can be used whenever they need it.

**Comment by niks3089** [comment]
Ok, so we can't delete the link as well. Lets keep this ticket open and close it based on feedback

**Comment by niks3089** [comment]
No comments received on this. Closing.
